### ISSUE TITLE
Error about Norm KR missing?

### ISSUE THREAD

**Issue by shuzhangcourage** [PouletAxel/SIP#1]
Dear talent possessor, I met a problem when I used this SIP, the problem was Norm KR missing (NULL) then script stopped running. I used default parameters. But if I change the resolution to 10kb that is fine. Do you maybe now why I can't use 5kb and why norm is missing? Thanks a lot!

**Comment by PouletAxel** [comment]
Hi Shu
Thanks for using SIP.

Could you give us more information: 
1. Do you know if in your hic file the KR Normalization is present or not for 5kb resolution bins (you can test )? If juicer cannot dump out the KR normalized reads then it is normal that SIP stopped running because it needs those files.
2. If your KR normalization is missing in hic file for 5kb and not 10kb, can you test to run SIP with Norm NONE at 5kb resolution?

Axel

**Comment by shuzhangcourage** [comment]
Hi Axel,
thank you for your answer. 
1. I generate my hic file by juicertools, I think I have KR Normalization in my hic file. I can call other chromosomes with 5kb, KR, except chromosome 18. 
2. I tried to run on chromosome18, 5kb, NONE.  That is work. 

Is it because my reads are not enough on that chromosome? I have total  around 1 billion reads. 
I think I can run other chromosomes with KR, and chromosome 18 with NONE. 
Thanks a lot!  
Shu

**Comment by PouletAxel** [comment]
Yes it is because you don't have enough reads for juicer to perform KR normalization on this chromosome.
